[package]
name = "microharness"
version = "0.1.1"
edition = "2024"
description = "A minimal agentic harness for local Ollama serve"

[dependencies]
anyhow = "1"
futures-util = "0.3"
reqwest = { version = "0.13", features = ["stream", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
